development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: intranet
  pool: 5
  username: postgres
  password: Server01*

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: intranet_dev
  pool: 5
  username: postgres
  password: Server01*