development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: intranet_credicope
  pool: 5
  username: postgres
  password: Server01*

test:
  adapter: postgresql
  encoding: unicode
  database: intranet_credicope_dev
  pool: 5
  host: localhost
  username: postgres
  password: Server01*